### PR TITLE
remove invalid email from error reporting green screen

### LINKED ISSUE #11: email in crash report text is no longer valid
The email address [solid@projects.palaso.org](mailto:solid@projects.palaso.org) is no longer valid.  We should replace this with something that users can contact us on.

### PR DESCRIPTION
**Pull request by megahirt**
fixes #11 

This removes the old invalid email address from the error reporting green screen.  Now, no email is shown in the dialog.  Users are expected to create a GitHub issue.

Before: 
image

After:
image

### CODE REVIEW

File: src/SolidGui/Program.cs [hunk 1]
```diff
@@ -95,7 +95,6 @@ private static void SetupErrorHandling()
         {
             ExceptionHandler.Init(new WinFormsExceptionHandler());
             Logger.Init();
-            ErrorReport.Init("solid@projects.palaso.org");
```
Comment (josephmyers) [inline src/SolidGui/Program.cs:98]: I believe you also need to remove the nearby dropdown containing the "email" option.

**Review by josephmyers — CHANGES_REQUESTED** [review]
This whole user experience is pretty subpar, and removing the email makes it all the more evident. Moving forward, how are they expected to know to log this in GitHub? Realistically, this is a recipe for snuffing out any remnant of issue reporting.

That said, I believe the expectation level for this software is quite low. We may not really care about all this.

**Comment by megahirt** [comment]
> That said, I believe the expectation level for this software is quite low. We may not really care about all this.

Yeah that's right.  Users of Solid should know that there isn't much support (we won't offer a dedicated support email) but the few people who use this, mostly DLS folks, should know that they can report issues on GitHub or on the community site.  We haven't fixed any bugs for years :( so expectation is quite low.  If I could easily make a note to that effect on the winforms error reporter, I would.  But it's a generic palaso winforms thing that I don't want to customize at this point.

File: src/SolidGui/Program.cs (hunk 1 above)
Comment (megahirt) [reply src/SolidGui/Program.cs:98]: That sounds like a great idea, however the windows forms dialog is part of SIL.Windows.Forms in libpalaso and, having a look at https://github.com/sillsdev/libpalaso/blob/e5745ec04c507a18bfe6b67c29c177713ec1a15d/SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs#L284 the private method setupMethodCombo() where the combo box is populated is not customizable or exposed.  So that would require more coordination to release a new version of libpalaso with changes that accommodate what we'd like.  So basically not worth the effort at this point.

Thanks for thinking about that though.

**Review by josephmyers — APPROVED** [review]
